### ISSUE TITLE
Setup hibernate.config.xml

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#10]
Create and configure hibernate.config.xml  with appropriate drivers, dialect, db url and other properties.

**Comment by milantrehan** [comment]
Created a folder src/main/resources and added hibernate.cfg.xml file.
@n8bc0der  @KhaaalDrogo - Update xml settings as per your systems -   Make sure the port number in xml is same as  the one Mysql is running on in your systems ( 3306 by default) . Also make sure to have a database named ironManSocial in your Mysql DBMS.

**Comment by n8bc0der** [comment]
port number same.
password updated for MySQL.
Database created.
