### ISSUE TITLE
Create docs folder in the root. Add database entities relations diagram file

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#11]
Create a folder named docs to be placed at the root.  It should be outside of any project just where readme is placed( don't place it inside ironmansocial). 

The directory will be used to keep documentations  and project related diagrams.

Create a file named DBEntities.doc using word ( or any other txt file format) having the ER diagram showing the relationship with USER, POST and COMMENT classes. Commit this file to the docs folder created above.

**Comment by n8bc0der** [comment]
Folder created & pushed to repository.
Need to work on ER Diagram/Use case if needed.
