### ISSUE TITLE
Configure Post class to be a hibernate entity

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#14]
Add appropriate annotations.
Class should have a primary key ( @id field is required over username - can use genratedtype over postid)
Primary key ( as decided for User) - > postId
Add column names with @column
Map this class to Comment ( one to many)
Map this class to user ( many to one)
Test using AppTest -> validate that post table is created with valid entries in DB.

**Comment by n8bc0der** [comment]
Conifgured Post class as a Hibernate Entity.
Need to add generatedtype annotation for ID and use mapping for User(Many to One) & Comment(One to Many)

**Comment by n8bc0der** [comment]
*Configured

**Comment by milantrehan** [comment]
Working fine. Any further change could be added through another ticket. Closing this.
