### ISSUE TITLE
Configure Comment to be a hibernate entity

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#15]
Add appropriate annotations.
Class should have a primary key ( @id field is required over username - can use genratedtype over commentid)
Primary key ( as decided for User) - > commentId
Add column names with @column
Map this class to Post ( many to one)
Map this class to User ( many to one)
Test using AppTest -> validate that post table is created with valid entries in DB.

**Comment by n8bc0der** [comment]
Configured Comment class as a Hibernate Entity.
Need to add generatedtype annotation for ID and use mapping for Post(One to Many) & User(Many tot One)

**Comment by milantrehan** [comment]
- adding @SequenceGenerator over User and comment classes
- modifying User_name column to be named as Username in User class
- changes to AppTest

**Comment by milantrehan** [comment]
Working fine. Any further change could be added through another ticket. Closing this.
