### ISSUE TITLE
AppTest: Implement pagination using HQL

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#18]
Write a method in AppTest that accepts two parameters (  startingValue , numberOfRecords).
Purpose of the method is to fetch and print the usernames from User table, but only over a limited scope.
The method will fetch records/rows starting from the **startingValue** till the number of records are less than or equal to **numberOfRecords**
Eg If startingValue  = 4 and numberOfRecords = 5
The method will fetch and print the usernames starting from row 4  and till row 8. ( the startingValue row is inclusive)

Code, test and then comment the calling code in main() of AppTest.

The names of parameters are just indicative ( can use any different name)

**Comment by n8bc0der** [comment]
Added the method for test to fetch username for the userID from startingValue to the asking records.
Added Post functionality for Post Description as per the range b/w postID.
Closing the task.
