### ISSUE TITLE
Edit ReadMe.md

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#2]
Edit ReadMe.md to have basic information of the project and the technologies to be used.

**Comment by n8bc0der** [comment]
1. Add description of project.
2. Relevant updates(changes, if any) to project.
3. MySQL version.
4. Hibernate version.
5. Maven details.
6. Tomcat details.

**Comment by milantrehan** [comment]
@n8bc0der Assigning this to you

**Comment by n8bc0der** [comment]
Added details except Maven.(need to check)
Changed card from To do -> In progress

**Comment by milantrehan** [comment]
This seems complete . closing this.
