### ISSUE TITLE
User Entity is not being saved with correct User id

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#22]
The User id values being generated while saving a user are not being incremented. All the user rows are being populated with user_id as 0 - see screenshot ).

![Screenshot 2020-03-09 at 9 36 07 PM](https://user-images.githubusercontent.com/6944246/76234838-456e8c80-6250-11ea-8327-6992670298a4.png)

**Comment by n8bc0der** [comment]
Added columnDefinition property of @Column annotation.
userID now generating automatically.
Closing the task.
