### ISSUE TITLE
Edit User class

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#3]
- Identify the instance variables for User class ( user will have references of Post and Comment as well - will need to use collection of Post and Comment, can go with ArrayList  data type for now) 

- Add the fields and setters and getters

**Comment by milantrehan** [comment]
also add a constructor with fields

**Comment by n8bc0der** [comment]
Created ArrayList of Post & Comment Class.

**Comment by n8bc0der** [comment]
Need to add fields for userStamp of type String and timeStamp of type Date and update Constructor with the added fields.
Remove the fields from Constructor in future if not required.

**Comment by milantrehan** [comment]
Completed. Closing this
