### ISSUE TITLE
Edit Comment class

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#4]
Identify and code instance variables for Comment class
- A comment will have reference to user who made the comment  and description (String) , and maybe more fields.
- A comment will have reference to user
- A comment should have a method getUserId to return the userId of the user who made the comment.
- add getters and setters

**Comment by milantrehan** [comment]
also add a constructor with fields

**Comment by n8bc0der** [comment]
Created & Pushed Comment Class with Constructor

**Comment by n8bc0der** [comment]
Need to add fields for userStamp of type String and timeStamp of type Date and update Constructor with the added fields.
Remove the fields from Constructor in future if not required.

**Comment by milantrehan** [comment]
Completed. Closing this
