### ISSUE TITLE
Edit Post Class

### ISSUE THREAD

**Issue by milantrehan** [n8bc0der/IronMan#5]
Identify and code instance variables for Post class

A post will have reference to User who added the post and description ( let's use basic String as data type for now) , and maybe more fields.
A post will have reference to user
A post should have a method getUserId to return the userId of the user who made the comment.
add getters and setters

**Comment by milantrehan** [comment]
also add a constructor with fields

**Comment by n8bc0der** [comment]
Created & Pushed Post Class with Constructor

**Comment by n8bc0der** [comment]
Need to add fields for userStamp of type String and timeStamp of type Date and update Constructor with the added fields.
Remove the fields from Constructor in future if not required.

**Comment by milantrehan** [comment]
Completed. Closing this
